config:
    capacity: 10000
    request:
        validator:
            dir-name:
                min: 1
                max: 255
            path-name:
                min: 2
                max: 4096
            owner-group-name:
                min: 1
                max: 100
            size:
                min: 1
                max: 100
        create-parents:
            limit: 10
